services:
  - type: web
    name: hello-world-api
    runtime: python
    repo: https://github.com/Harish018S/hello_world
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vicky_server:app  # For Flask
    envVars:
      - key: PORT
        value: 10000
